defaults:
    - backbone: CNN14
    - transformer: torch_Transformer_API
    
type: 'CombinedModel_Av2_Teacher' #All options are avliable in models/instrument_detection/combined.py
task: 'Softmax'

model:
    args:
        num_classes: ${MIDI_MAPPING.plugin_labels_num}
        num_Q: 39
        feature_weight: 0.1
        d_model: 256
        dropout: 0.2
    positional:
        temperature: 10000
        normalize: True
        scale: null
    optimizer:
        lr: ${lr}
        eps: 1e-08
        weight_decay: 0.0
        amsgrad: True
    eos_coef: 0.1
    shuffle_target: False
    target_dropout: 0
    scale_logits: False
    
evaluate:
    max_evaluation_steps: 100
 