type: 'OpenMicBaseline' #All options are avliable in models/instrument_detection/combined.py
task: 'BinaryOpenMic'

model:
    args:
        freq_bins: ${feature.STFT.n_mels}
        classes_num: ${MIDI_MAPPING.plugin_labels_num}
        emb_layers: 3
        hidden_units: ${feature.STFT.n_mels}
        drop_rate: 0.6
    optimizer:
        lr: ${lr}
        eps: 1e-08
        weight_decay: 0.0
        amsgrad: True
    eos_coef: 0.1
    
evaluate:
    max_evaluation_steps: 100
 