defaults:
    - feature: SS_STFT
model:
    type: "CondUNet"
    args:
        channels_num: 1
        condition_size: ${MIDI_MAPPING.plugin_labels_num}
        is_gamma: False
        is_beta: True
    loss_types: 'l1_wav'

evaluation:
    max_evaluation_steps: 100
    onset_threshold: 0.1
    offset_threshod: 0.1
    frame_threshold: 0.1
    pedal_offset_threshold: 0.2
    modeling_offset: ${transcription.model.args.modeling_offset}
    seg_batch_size: 8
    checkpoint_path: '/opt/tiger/kinwai/jointist/outputs/SS_Weights/2022-01-20_18-46-27_CondUNet-3p1n-csize=40/CondUNet-3p1n-csize=40/version_0/checkpoints/last.ckpt'
    output_path: null
    
batchprocess:
    MIDI_MAPPING: ${MIDI_MAPPING}
    mode: ${inst_sampler.mode}
    temp: ${inst_sampler.temp}
    samples: ${inst_sampler.samples}
    neg_samples: ${inst_sampler.neg_samples}
    audio_noise: ${inst_sampler.audio_noise}
    transcription: ${transcription}
    source_separation: ${source}    