type: 'DETR_Transformerv2'
args:
    d_model: 256
    dropout: 0.2
    nhead: 8
    dim_feedforward: 2048
    num_encoder_layers: 0
    num_decoder_layers: 1
    normalize_before: False
    return_intermediate_dec: True