type: 'torch_Transformer_API'
args:
    d_model: 256
    dropout: 0.1
    nhead: 8
    dim_feedforward: 2048
    num_encoder_layers: 0
    num_decoder_layers: 1
    norm_first: False
    batch_first: True