gpus: 1 # choose your GPU
audio_path: 'audio_path=/opt/tiger/kinwai/jointist/songs' # need to use absolute path
audio_ext: 'mp3' # mp3, wav, flac, anything that torchaudio.load supports
seg_batch_size: 8 # only use during inference 
frames_per_second: 100
segment_seconds: 10
lr: null
h5_name: 'ballroom_audio.h5' # valid only when datamodule=h5 is selected
h5_root: '/opt/tiger/kinwai/jointist/sheetdoctor' # valid only when datamodule=h5 is selected

            
MIDI_MAPPING: # This whole part will be overwritten in the main code 
    type: 'MIDI_class'
    plugin_labels_num: 0
    NAME_TO_IX: 0
    IX_TO_NAME: 0

checkpoint:
  tseparation: 'weights/tseparation.ckpt'
  detection: "weights/MTT.ckpt"

trainer:
  gpus: ${gpus}
  accelerator: 'ddp'
  sync_batchnorm: True
  replace_sampler_ddp: False
  profiler: 'simple'
  

defaults:
  - datamodule: wild
  - detection: CombinedModel_NewCLSv2
  - separation: TCUNet
  - transcription: Original    
